[package]
name = "glassfish_mc"
version = "0.1.0"
edition = "2021"
authors = ["Sullivan Bognar"]

[dependencies]
log = "0.4.14"
fern = { version = "0.6.0", features = ["colored"] }
toml = "0.5.8"
chrono = "0.4.19"
serde = { version = "1.0.130", features = ["derive"] }
